# Generated by Django 4.1.7 on 2023-03-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_app', '0002_rename_myform_myformmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyFormModel',
            new_name='User',
        ),
    ]
